repos:

# remove unused python imports
-   repo: https://github.com/myint/autoflake.git
    rev: v1.4
    hooks:
    -   id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--ignore-init-module-imports"]

# sort imports
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort

# code format according to black
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black

# # check for python styling with flake8
# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.9.2
#     hooks:
#     -   id: flake8
#         additional_dependencies: [
#           'flake8-docstrings',
#           'flake8-bugbear',
#           'flake8-comprehensions',
#           'flake8-simplify',
#         ]

# cleanup notebooks
-   repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
    -   id: nbstripout
